version: "3.8"

    
networks:
  filetransfer:

services:
  api:
    build:
      context: ./app/
      dockerfile: Dockerfile
      target: base
    restart: always
    volumes:
      - ./app/src:/home/node/app/src
    environment:
      - HOST=databases
      - PORT=5432
      - USER=root
      - PASSWORD=root
      - PROCESSINGDB=db_processing
      - TRANSACTIONALDB=db_transactional
    container_name: api
    expose:
      - '5002'
    ports:
      - '5002:5002'
    networks:
      - filetransfer
    command: npm run dev
    
  databases:
    build: ./databases/
    container_name: databases
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    networks:
      - filetransfer
    ports: 
      - "3310:5432"
    volumes:
      - ./databases/jsonFiles/:/docker-entrypoint-initdb.d/jsonFiles/
      - ./databases/db_processing.sql:/docker-entrypoint-initdb.d/db_processing.sql
      - ./databases/db_transactional.sql:/docker-entrypoint-initdb.d/db_transactional.sql
      
  pgadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "3380:80"
    networks:
      - filetransfer
    depends_on:
      - databases

  ftp-daemon:
    build:
      context: ./daemon/
      dockerfile: Dockerfile
    restart: always
    container_name: ftp-daemon
    networks:
      - filetransfer
    volumes:
      - ./daemon:/daemon
    environment:
      
      HOST: databases
      PORT: 5432
      USER: root
      PASSWORD: root
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    command: ["crond", "-l", "2", "-f"]